### ISSUE TITLE
We are getting set-env issue in Github actions

### ISSUE THREAD

**Issue by RameshNagaiyar** [zyborg/gh-action-buildnum#2]
![image](https://user-images.githubusercontent.com/22591122/99670067-f68f1d00-2a95-11eb-940e-d63bdad35cf3.png)

Kindly give me a suggestion to resolve the issue.

**Comment by ebekker** [comment]
Yikes!  Looks like I missed this change:  https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by ebekker** [comment]
This should be fixed now, several other projects have tested it and it seems to be working correctly.

**Comment by RameshNagaiyar** [comment]
Thanks for your quick response 😊. It is working fine 👍.
